<?xml version="1.0"?>
<package format="3">
  <name>desktop_arm</name><version>0.1.0</version>
  <description>Four-DOF robot arm gripping and positioning mechanism design with ROS 2 motion control</description>
  <maintainer email="935093784@qq.com">赖根涛</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_python</buildtool_depend>
  <exec_depend>rclpy</exec_depend><exec_depend>control_msgs</exec_depend>
  <exec_depend>trajectory_msgs</exec_depend><exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend><exec_depend>std_msgs</exec_depend>
  <exec_depend>std_srvs</exec_depend><exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>launch_ros</exec_depend><exec_depend>rviz2</exec_depend>
  <export><build_type>ament_python</build_type></export>
</package>
